---
name: Cloudflare Argo Tunnel - Zero Trust
version: 2.2
slug: cloudflare-argo-zerotrust
url: https://github.com/paocloud/hass-cloudflare-argo
description: Connect to Cloudflare Argo tunnel to Home Assistant instance.
codenotary: hello@paocloud.co.th
arch: 
  - armv7
  - amd64
  - aarch64
  - armhf
  - i386
startup: application
hassio_api: true
boot: auto
host_network: true
apparmor: true
init: false
options:
  token: ""
schema:
  token: str
